version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: grfooddb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/grfooddb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_LIQUIBASE_ENABLED: "false"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - my-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  mariadb_data:

networks:
  my-network:
    driver: bridge